# Renders the html page

name: render-page

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [ main ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2.2.0

        # Install the template engine
        - uses: BSFishy/pip-action@v1
          with:
              packages: jinja2

        # Run the python script
        - name: Render html
          run: python render.py

        - name: Make public dir and copy files
          run: |
              mkdir public
              cp -r css/ public
              cp -r assets/ public
              cp index.html public/index.html

        - name: GitHub Pages
          uses: crazy-max/ghaction-github-pages@v2.2.0
          with:
            build_dir: public
            target_branch: gh-pages
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
